chore: test

diff --git a/.github/workflows/snyk-code-scanning.yml b/.github/workflows/snyk-code-scanning.yml
--- a/.github/workflows/snyk-code-scanning.yml
+++ b/.github/workflows/snyk-code-scanning.yml
@@ -26,47 +26,36 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Set up Snyk CLI to check for security issues
-        # Snyk can be used to break the build when it detects security issues.
-        # In this case we want to upload the SAST issues to GitHub Code Scanning
-        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
-
-      - name: Setup JDK
-        uses: actions/setup-java@v4
-        with:
-          java-version: ${{ env.JAVA_VERSION }}
-          distribution: "temurin"
-
-      - name: Setup Gradle
-        uses: gradle/gradle-build-action@v2
-
-      - name: Validate Gradle wrapper
-        uses: gradle/wrapper-validation-action@v1
-
       - name: Run Snyk to check for Gradle vulnerabilities
         uses: snyk/actions/gradle@master
+        continue-on-error: true # To make sure that SARIF upload gets called
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
         with:
           args: --severity-threshold=high --sarif-file-output=snyk-gradle.sarif
 
-        # Runs Snyk Code (SAST) analysis and uploads result into GitHub.
-        # Use || true to not fail the pipeline
-      - name: Snyk Code test
-        run: snyk code test --sarif > snyk-code.sarif # || true
-        env:
-          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+      #      - name: Set up Snyk CLI to check for security issues
+      #        # Snyk can be used to break the build when it detects security issues.
+      #        # In this case we want to upload the SAST issues to GitHub Code Scanning
+      #        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
 
-        # Runs Snyk Open Source (SCA) analysis and uploads result to Snyk.
-      - name: Snyk Open Source monitor
-        run: snyk monitor --all-projects
-        env:
-          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+#        # Runs Snyk Code (SAST) analysis and uploads result into GitHub.
+#        # Use || true to not fail the pipeline
+#      - name: Snyk Code test
+#        run: snyk code test --sarif > snyk-code.sarif # || true
+#        env:
+#          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+#
+#        # Runs Snyk Open Source (SCA) analysis and uploads result to Snyk.
+#      - name: Snyk Open Source monitor
+#        run: snyk monitor --all-projects
+#        env:
+#          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
 
-      - name: Upload Snyke Code result to GitHub Code Scanning
-        uses: github/codeql-action/upload-sarif@v3
-        with:
-          sarif_file: snyk-code.sarif
+#      - name: Upload Snyke Code result to GitHub Code Scanning
+#        uses: github/codeql-action/upload-sarif@v3
+#        with:
+#          sarif_file: snyk-code.sarif
 
       - name: Upload Snyk Gradle result to GitHub Code Scanning
         uses: github/codeql-action/upload-sarif@v3
